### PR TITLE
build: removes stream package by using stream-browserify

### PR DESCRIPTION
**Pull request by shawnzhu**
## Motivation

when bundling my app that depends on `@lhncbc/ucum-lhc` via esbuild, it will include the stream package from `node_modules/stream` instead of using the `stream` package from node runtime because `require('stream')` was transpiled as `require('node_modules/stream')`.

when using `@lhncbc/ucum-lhc` on node, it doesn't need the npm package `stream`.
when using `@lhncbc/ucum-lhc` on browser, it could use the `stream-browserify` instead since it's in devDependencies already.

### CODE REVIEW

**Comment by plynchnlm** [comment]
It looks to me like "stream" is not even used by the ucum-lhc.js browser distribution file or the files in "source", but only by the files in the impexp sudirectory which is a utility program for updating the data that is only run in a node environment.  So, I don't think the change will affect the browser builds, but it does at least remove an unnecessary dependency.

**Comment by plynchnlm** [comment]
This now merged, though somehow in the process of merging, the commit SHA changed, which is why this doesn't look merged.  However, you will find https://github.com/LHNCBC/ucum-lhc/commit/d5159f38dcf877ccac10935663408e83aa77cadd on the master branch.

**Comment by shawnzhu** [comment]
@plynchnlm thank you. may I ask when it cuts a new release that include this change?

**Comment by plynchnlm** [comment]
It is in 7.0.0 (already released).

**Pull request closed without merging**
